/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserLoginDto
 */
export interface UserLoginDto {
    /**
     * 
     * @type {string}
     * @memberof UserLoginDto
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UserLoginDto
     */
    password?: string;
}

/**
 * Check if a given object implements the UserLoginDto interface.
 */
export function instanceOfUserLoginDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserLoginDtoFromJSON(json: any): UserLoginDto {
    return UserLoginDtoFromJSONTyped(json, false);
}

export function UserLoginDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserLoginDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': !exists(json, 'username') ? undefined : json['username'],
        'password': !exists(json, 'password') ? undefined : json['password'],
    };
}

export function UserLoginDtoToJSON(value?: UserLoginDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'password': value.password,
    };
}

