/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CategorityVo
 */
export interface CategorityVo {
    /**
     * 
     * @type {number}
     * @memberof CategorityVo
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CategorityVo
     */
    name?: string;
}

/**
 * Check if a given object implements the CategorityVo interface.
 */
export function instanceOfCategorityVo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CategorityVoFromJSON(json: any): CategorityVo {
    return CategorityVoFromJSONTyped(json, false);
}

export function CategorityVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategorityVo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function CategorityVoToJSON(value?: CategorityVo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

