version: "3"

services:
  nginx:
    image: nginx
    ports:
      - 80:80
  springboot:
    image: springboot
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
    volumes:
      - ./appdata/springboot:/app

  nextjs:
    image: nextjs
    depends_on:
      - springboot

  mysql:
    image: "mysql:latest"
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: blog
      MYSQL_USER: jiajun
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_password
      - db_root_password
    volumes:
      - ./appdata/mysql:/var/lib/mysql

  # minio:
  #   image: "bitnami/minio:latest"
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   environment:
  #     MINIO_ROOT_USER: minio-root-user
  #     MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio-root-password
  #   secrets:
  #     - oss_password
  #     - oss_root_password

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
  oss_password:
    file: ./secrets/oss_password.txt
  oss_root_password:
    file: ./secrets/oss_root_password.txt
