# Use OpenJDK 11 as the base image
FROM openjdk:21 AS base

# Create a new stage for dependencies (if needed)
FROM base AS deps


WORKDIR /app
ADD /uploads /uploads
# Set the timezone
ENV TZ=America/Vancouver
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Add your application JAR file
ADD target/blog-0.0.1-SNAPSHOT.jar app.jar

# Run commands to set up the application
RUN bash -c 'touch /app.jar'

# Expose port 8080 (if your application uses this port)
EXPOSE 8080

# Define a volume (if needed)
VOLUME /uploads


# Specify the entry point for running the application
CMD ["java", "-jar", "app.jar"]
