version: "3"

services:
  nginx:
    build:
      context: ../nginx
      dockerfile: ../docker/Dockerfile-nginx
    ports:
      - 80:80

  springboot:
    image: springboot
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile-backend
    restart: always
    ports:
      - 8080:8080

  nextjs:
    image: nextjs
    build:
      context: ../frontend-next
      dockerfile: ../docker/Dockerfile-frontend
    depends_on:
      - springboot
