/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserRegistorDto
 */
export interface UserRegistorDto {
    /**
     * 
     * @type {string}
     * @memberof UserRegistorDto
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegistorDto
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegistorDto
     */
    nickname?: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegistorDto
     */
    email?: string;
    /**
     * 
     * @type {Date}
     * @memberof UserRegistorDto
     */
    createTime?: Date;
}

/**
 * Check if a given object implements the UserRegistorDto interface.
 */
export function instanceOfUserRegistorDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserRegistorDtoFromJSON(json: any): UserRegistorDto {
    return UserRegistorDtoFromJSONTyped(json, false);
}

export function UserRegistorDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRegistorDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': !exists(json, 'username') ? undefined : json['username'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'nickname': !exists(json, 'nickname') ? undefined : json['nickname'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'createTime': !exists(json, 'createTime') ? undefined : (new Date(json['createTime'])),
    };
}

export function UserRegistorDtoToJSON(value?: UserRegistorDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'password': value.password,
        'nickname': value.nickname,
        'email': value.email,
        'createTime': value.createTime === undefined ? undefined : (value.createTime.toISOString()),
    };
}

